# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QFont
import sys
import psycopg2
from psycopg2 import sql
import window1

# подключение к БД
conn = psycopg2.connect(dbname="project_db", user="postgres",
                        password="17042008", host="localhost", port="5433")
cursor = conn.cursor()
login = ""
password = ""
registred = False

# картинки
chem_pics = {
    1: "src/img/chem_pics/avogadro.png",
    2: "src/img/chem_pics/carbon.jpg",
    3: "src/img/chem_pics/Mercury.jpg",
    4: "src/img/chem_pics/natrii.jpg",
    5: "src/img/chem_pics/plumbum.jpg",
    6: "src/img/chem_pics/plutonium.jpg",
    7: "src/img/chem_pics/silicium.jpg",
    8: "src/img/chem_pics/mishyak.jpg",
    9: "src/img/chem_pics/molibden.jpg",
    10: "src/img/chem_pics/aurum.jpg"
}

bio_pics = {
    1: "src/img/bio_pics/",
    2: "src/img/bio_pics/",
    3: "src/img/bio_pics/",
    4: "src/img/bio_pics/",
    5: "src/img/bio_pics/",
    6: "src/img/bio_pics/",
    7: "src/img/bio_pics/",
    8: "src/img/bio_pics/",
    9: "src/img/bio_pics/",
    10: "src/img/bio_pics/"
}

math_pics = {
    1: "src/img/math_pics/",
    2: "src/img/math_pics/",
    3: "src/img/math_pics/",
    4: "src/img/math_pics/",
    5: "src/img/math_pics/",
    6: "src/img/math_pics/",
    7: "src/img/math_pics/",
    8: "src/img/math_pics/",
    9: "src/img/math_pics/",
    10: "src/img/math_pics/"
}

it_pics = {
    1: "src/img/it_pics/",
    2: "src/img/it_pics/",
    3: "src/img/it_pics/",
    4: "src/img/it_pics/",
    5: "src/img/it_pics/",
    6: "src/img/it_pics/",
    7: "src/img/it_pics/",
    8: "src/img/it_pics/",
    9: "src/img/it_pics/",
    10: "src/img/it_pics/"
}

eng_pics = {
    1: "src/img/eng_pics/",
    2: "src/img/eng_pics/",
    3: "src/img/eng_pics/",
    4: "src/img/eng_pics/",
    5: "src/img/eng_pics/",
    6: "src/img/eng_pics/",
    7: "src/img/eng_pics/",
    8: "src/img/eng_pics/",
    9: "src/img/eng_pics/",
    10: "src/img/eng_pics/"
}
# ответы
chem_ans = {
    1: "число авогадро",
    2: "углерод",
    3: "ртуть",
    4: "натрий",
    5: "свинец",
    6: "плутоний",
    7: "кремний",
    8: "мышьяк",
    9: "молибден",
    10: "золото"
}

bio_ans = {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: ""
}

math_ans = {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: ""
}

it_ans = {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: ""
}

eng_ans = {
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "",
    7: "",
    8: "",
    9: "",
    10: ""
}
# хранение использованных заданий
used_chem = []
used_bio = []
used_math = []
used_it = []
used_eng = []


def removeAll(self):
    self.lineEdit.deleteLater()
    self.lineEdit = None
    self.lineEdit_2.deleteLater()
    self.lineEdit_2 = None
    self.label.deleteLater()
    self.label = None
    self.label_2.deleteLater()
    self.label_2 = None
    self.pushButton.deleteLater()
    self.pushButton = None
    self.pushButton_2.deleteLater()
    self.pushButton_2 = None


def createNew(self):
    # сделать основное окно
    pass


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color:#787878")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")

        font = QFont(
            "Arial",
            12
        )

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 200, 191, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setFont(font)

        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 248, 191, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setFont(font)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(248, 200, 51, 21))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(237, 250, 61, 16))
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 310, 191, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.enter)
        self.pushButton.setStyleSheet("background-color: #fff;")
        self.pushButton.setFont(font)

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 360, 191, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.register)
        self.pushButton_2.setStyleSheet("background-color: #fff;")
        self.pushButton_2.setFont(font)

        # еррор генератор
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 450, 351, 41))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: red;")
        self.label_3.setObjectName("label_3")

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.label.setBuddy(self.lineEdit)
        self.label_2.setBuddy(self.lineEdit_2)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def enter(self):
        global registred
        login = self.lineEdit.text()
        password = self.lineEdit_2.text()
        query_vaild = sql.SQL("SELECT * FROM users WHERE nickname = %s AND password = %s")
        if login == "" or password == "":
            self.label_3.setText("Введите логин и пароль!")
            registred = False
        else:
            try:
                cursor.execute(query_vaild, (login, password))
                record = cursor.fetchall()
                if record != []:
                    print("Вход выполнен успешно!\n")
                    self.label_3.setText("")
                    self.label_3.setStyleSheet("display:none;")
                    registred = True
                    # удаление старого лейаута
                    removeAll(self)
                else:
                    self.label_3.setText("Неправильный логин или пароль!")
                    registred = False
            except psycopg2.Error:
                self.label_3.setText("Для пароля можно использовать только цифры!")

    def register(self):
        global registred
        login = self.lineEdit.text().strip()
        password = self.lineEdit_2.text().strip()
        find_query_login = sql.SQL("SELECT * FROM users WHERE nickname = %s")
        query_insert = sql.SQL(
            "INSERT INTO users (nickname, password) VALUES (%s, %s)")
        # базовый чек
        if not login or not password:
            self.label_3.setText("Логин и пароль не могут быть пустыми!")

        cursor.execute(find_query_login, (login,))
        if cursor.fetchone():
            self.label_3.setText(
                "Ошибка: Пользователь с таким логином уже существует!")

        # Если без ошибок
        try:
            cursor.execute(query_insert, (login, password))
            conn.commit()
            print("Вы успешно зарегистрированы!")
            self.label_3.setText("")
            self.label_3.setStyleSheet("display:none;")
            registred = True
            # удаление старого лейаута
            removeAll(self)
        except psycopg2.Error as exception:
            conn.rollback()
            print(f"Ошибка при регистрации: {exception}")
            self.label_3.setText("Ошибка при регистрации")
            registred = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Speech Recognition App"))
        self.label.setText(_translate("MainWindow", "Логин:"))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.pushButton_2.setText(_translate(
            "MainWindow", "Зарегистрироваться"))


def main(correct_answers):
    app = QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main(0)
